name: Run Unit Tests (with Coverage)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Coverage - Node.js ${{ matrix.node-version }}

    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }} environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run coverage check
        run: yarn coverage
